Repository Nexters/phochak-iOS, pull requests merged in 2023-03, with the labels that each got.

#34 feat: 닉네임 변경 뷰 서버 연동, Request 함수 버그 수정
  Targets/DesignKit/Sources/Views/PhoChakAlertViewController.swift
  Targets/Domain/Sources/DomainAssembly.swift
  Targets/Domain/Sources/Interfaces/ProfileSettingServiceType.swift
  Targets/Domain/Sources/UseCases/ProfileSettingUseCase.swift
  Targets/Domain/Sources/UseCases/UploadVideoPostUseCase.swift
  Targets/Feature/Sources/Common/AppCoordinator.swift
  Targets/Feature/Sources/Common/Classes/SceneFactory.swift
  Targets/Feature/Sources/MyPage/Reactor/MyPageReactor.swift
  Targets/Feature/Sources/MyPage/View/MyPageViewController.swift
  Targets/Feature/Sources/ProfileSetting/Reactor/ProfileSettingReactor.swift
  Targets/Feature/Sources/ProfileSetting/View/ProfileSettingViewController.swift
  Targets/Feature/Sources/VideoUpload/Reactor/UploadVideoPostReactor.swift
  Targets/Service/Sources/APIs/ProfileSettingAPI.swift
  Targets/Service/Sources/Extension/Reactive+.swift
  Targets/Service/Sources/PhoChakNetworkResult.swift
  Targets/Service/Sources/Response/ChangeNickNameResponse.swift
  Targets/Service/Sources/Response/CheckDuplicationResponse.swift
  Targets/Service/Sources/ServiceAssembly.swift
  Targets/Service/Sources/Services/ProfileSettingService.swift
Labels: bug, feature

#38 fix: QA 사항 반영
  Targets/DesignKit/Sources/Views/VIdeoPlayerView.swift
  Targets/Feature/Sources/Home/View/VideoPostCell.swift
  Targets/Feature/Sources/PostRolling/View/DetailPostCell.swift
  Targets/Feature/Sources/PostRolling/View/PostRollingViewController.swift
  Targets/Feature/Sources/VideoUpload/View/UploadVideoPostCell.swift
  Targets/PhoChak/Resources/Assets.xcassets/ImageSet/tab_home_selected.imageset/Contents.json
  Targets/PhoChak/Resources/Assets.xcassets/ImageSet/tab_home_selected.imageset/Icons.png
  Targets/PhoChak/Resources/Assets.xcassets/ImageSet/tab_home_selected.imageset/home_tab_selected.svg
  Targets/PhoChak/Resources/Assets.xcassets/ImageSet/tab_profile_selected.imageset/Contents.json
  Targets/PhoChak/Resources/Assets.xcassets/ImageSet/tab_profile_selected.imageset/Icons.png
  Targets/PhoChak/Resources/Assets.xcassets/ImageSet/tab_profile_selected.imageset/tab_profile_selected.svg
  Targets/PhoChak/Resources/Assets.xcassets/ImageSet/tab_videoUpload.imageset/Contents.json
  Targets/PhoChak/Resources/Assets.xcassets/ImageSet/tab_videoUpload.imageset/Icons.png
  Targets/PhoChak/Resources/Assets.xcassets/ImageSet/tab_videoUpload.imageset/Icons@2x.png
  Targets/PhoChak/Resources/Assets.xcassets/ImageSet/tab_videoUpload.imageset/Icons@3x.png
Labels: feature

#39 fix: 이슈 수정
  Targets/DesignKit/Sources/Views/VIdeoPlayerView.swift
  Targets/Feature/Sources/Home/View/HomeViewController.swift
  Targets/Feature/Sources/Home/View/VideoPostCell.swift
  Targets/Feature/Sources/PostRolling/View/HashTagListView.swift
  Targets/Feature/Sources/PostRolling/View/PostRollingViewController.swift
  Targets/PhoChak/Resources/Assets.xcassets/ImageSet/apple.imageset/Contents.json
  Targets/PhoChak/Resources/Assets.xcassets/ImageSet/apple.imageset/apple.png
  Targets/PhoChak/Resources/Assets.xcassets/ImageSet/apple.imageset/apple@2x.png
  Targets/PhoChak/Resources/Assets.xcassets/ImageSet/apple.imageset/apple@3x.png
Labels: bug

#41 fix: 홈과 상세에서의 좋아요 동기화 이슈
  Targets/DesignKit/Sources/Views/VIdeoPlayerView.swift
  Targets/Domain/Sources/Entities/VideoPost.swift
  Targets/Domain/Sources/Interfaces/VideoPostServiceType.swift
  Targets/Domain/Sources/UseCases/LikeVideoPostUseCase.swift
  Targets/Domain/Sources/UseCases/VideoPostUseCase.swift
  Targets/Feature/Sources/Home/Reactor/HomeReactor.swift
  Targets/Feature/Sources/Home/View/VideoPostCell.swift
  Targets/Service/Sources/Response/ResponseStatus.swift
  Targets/Service/Sources/Services/VideoPostService.swift
Labels: bug
