Repository Nexters/phochak-iOS, pull requests merged in 2023-04, with the labels that each got.

#43 fix: 홈에서 좋아요 터치시에도 마이페이지-내가포착한포스트 탭에 업데이트 안되는 현상 수정
  Targets/Feature/Sources/Home/Reactor/HomeReactor.swift
  Targets/Feature/Sources/Home/View/HomeViewController.swift
  Targets/Feature/Sources/MyPage/Reactor/MyPageReactor.swift
Labels: bug

#50 fix: #49 - 상세화면에서 홈으로 pop시 AffineTransform이 의도대로 동작하지 않는 현상
  Targets/Feature/Sources/Home/View/HomeViewController.swift
Labels: bug

#53 Feat: 로그인 화면 로고UI 구현
  Targets/DesignKit/Sources/Extensions/UIImage+.swift
  Targets/Feature/Sources/SignIn/View/SignInViewController.swift
  Targets/PhoChak/Resources/Assets.xcassets/ImageSet/loginIcon.imageset/Contents.json
  Targets/PhoChak/Resources/Assets.xcassets/ImageSet/loginIcon.imageset/Icons.png
  Targets/PhoChak/Resources/Assets.xcassets/ImageSet/loginIcon.imageset/Icons@2x.png
  Targets/PhoChak/Resources/Assets.xcassets/ImageSet/loginIcon.imageset/Icons@3x.png
  Targets/PhoChak/Resources/Assets.xcassets/ImageSet/loginLogo.imageset/Contents.json
  Targets/PhoChak/Resources/Assets.xcassets/ImageSet/loginLogo.imageset/Logo.png
  Targets/PhoChak/Resources/Assets.xcassets/ImageSet/loginLogo.imageset/Logo@2x.png
  Targets/PhoChak/Resources/Assets.xcassets/ImageSet/loginLogo.imageset/Logo@3x.png
  Targets/PhoChak/Resources/Assets.xcassets/ImageSet/loginTitle.imageset/Contents.json
  Targets/PhoChak/Resources/Assets.xcassets/ImageSet/loginTitle.imageset/loginTitle.png
  Targets/PhoChak/Resources/Assets.xcassets/ImageSet/loginTitle.imageset/loginTitle@2x.png
  Targets/PhoChak/Resources/Assets.xcassets/ImageSet/loginTitle.imageset/loginTitle@3x.png
Labels: feature

#55 refactor: #54 - 커스텀 Alert클래스 제거, Alertable 프로토콜 기반 사용 패턴 적용
  Targets/DesignKit/Sources/Buttons/UIApplication+.swift
  Targets/DesignKit/Sources/Extensions/Alertable+.swift
  Targets/DesignKit/Sources/Views/PhoChakAlertViewController.swift
  Targets/Feature/Sources/Common/AppCoordinator.swift
  Targets/Feature/Sources/Common/TabBar/PhoChakTabBarController.swift
  Targets/Feature/Sources/Home/View/HomeViewController.swift
  Targets/Feature/Sources/MyPage/View/MyPageViewController.swift
  Targets/Feature/Sources/PostRolling/Reactor/PostRollingReactor.swift
  Targets/Feature/Sources/PostRolling/View/PostRollingViewController.swift
  Targets/Feature/Sources/ProfileSetting/View/ProfileSettingViewController.swift
  Targets/Feature/Sources/VideoUpload/View/UploadVideoPostViewController.swift
Labels: refactor

#60 Refactor: 홈 & 상세에서 신고하기 버튼과 포착 버튼 터치 영역 늘리기
  Targets/DesignKit/Sources/Buttons/ExtendedTouchAreaButton.swift
  Targets/Feature/Sources/Home/View/VideoPostCell.swift
  Targets/Feature/Sources/PostRolling/View/HashTagListView.swift
Labels: refactor

#62 QA 버그 수정
  Targets/Feature/Sources/Common/TabBar/PhoChakTabBarController.swift
  Targets/Feature/Sources/MyPage/Reactor/MyPageReactor.swift
  Targets/Feature/Sources/MyPage/View/MyPageViewController.swift
  Targets/Feature/Sources/PostRolling/View/PostRollingViewController.swift
Labels: bug

#65 Feat: #64 - Fastlane 적용
  .gitignore
  Gemfile
  Gemfile.lock
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/Matchfile
  fastlane/README.md
Labels: feature
